### ISSUE TITLE
Bug Report: Application deployment failure cause DAS not restart

### ISSUE THREAD

**Issue by cidylong** [payara/Payara#6306]
### Brief Summary

Payara 6.2023.5 community version, jdk 17, 

Developed some custom libs by using java 9 modular by Netbeans 17 with maven. 

module-info.java developed with requires and exports to let other applications to use custom objects.

module-info.java as:

    module com.longz.thss.JpaModule {
      requires java.base;
      requires org.objectweb.asm.tree;
      requires com.hazelcast.core;
      requires jakarta.ejb.api;
      requires jakarta.faces.api;
      requires jakarta.cdi;
      requires jakarta.validation;
      requires jakarta.persistence;
      requires jakarta.servlet;
      requires jakarta.mail;
      requires jakarta.messaging;
      requires com.longz.thss.lib.ThssHzLibModule;
      requires com.longz.thss.GeoPlaceLib;
      requires java.naming;
      requires libphonenumber;
      requires primefaces;
      requires java.desktop;
      requires layout;
      requires kernel;
      requires io;
      requires com.google.gson;
      requires com.google.common;
      requires org.jfree.jfreechart;
      requires org.json;
      requires java.net.http;
    
      exports com.longz.thss.jpa.converter;
      exports com.longz.thss.jpa.entity;
      exports com.longz.thss.jpa.factory;
      exports com.longz.thss.jpa.mapstore;
      exports com.longz.thss.jpa.utils;
      exports com.longz.thss.jpa.impl;
      exports com.longz.thss.jpa.service;
      exports com.longz.thss.jpa.validator;
      exports com.longz.thss.integrate.sms.rest;
      exports com.longz.thss.ebj.rmi.smsd;
      exports com.longz.thss.ebj.rmi;
      exports com.longz.thss.ebj.rmi.jms;
    }

lib was compiled as JpaModule.jar

then load JpaModule.jar by using asadmin command as:

    ./asadmin add-library JpaModule.jar

verified by:

    ./asadmin list-libraries

Tried to develop a simple EJB module to access objects that defined in JpaModule.jar (libs). 

Tried to deploy EJBModule.jar into any server instance in the domain from Admin_UI

without success; error message from server instance log as:

    [2023-06-12T12:29:44.436+1000] [Payara 6.2023.5] [WARNING] [AS-DEPLOYMENT-00011][javax.enterprise.system.tools.deployment.dol] [tid: _ThreadID=113 _ThreadName=admin-thread-pool::admin-listener(1)]    [timeMillis: 1686536984436] [levelValue: 900] [[
      Error in annotation processing: {0}.
    java.lang.NoClassDefFoundError: com/longz/thss/ebj/rmi/PersonRemote
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1012)
	at com.sun.enterprise.loader.ASURLClassLoader.findClass(ASURLClassLoader.java:747)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
	at com.sun.enterprise.loader.CurrentBeforeParentClassLoader.loadClass(CurrentBeforeParentClassLoader.java:83)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
        .........
    Caused by: java.lang.ClassNotFoundException: com.longz.thss.ebj.rmi.PersonRemote
	at com.sun.enterprise.loader.ASURLClassLoader.findClassData(ASURLClassLoader.java:807)
	at com.sun.enterprise.loader.ASURLClassLoader.findClass(ASURLClassLoader.java:689)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
	at com.sun.enterprise.loader.CurrentBeforeParentClassLoader.loadClass(CurrentBeforeParentClassLoader.java:83)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 98 more
    ]]

and more error comes up.

The same code structure works fine in Payara 5.2021.X version

Deployment failure cause server instance need to restart, when I tried to restart domain by run 

    ./asadmin restart-domain production

DAS server failed to restart, error information as:

    [2023-06-12T12:36:15.925+1000] [Payara 6.2023.5] [SEVERE] [] [jakarta.enterprise.resource.webcontainer.jsf.config] [tid: _ThreadID=128 _ThreadName=Thread-13] [timeMillis: 1686537375925] [levelValue: 1000] [[
    Critical error during deployment: 
    java.lang.NoClassDefFoundError: javax/faces/context/FacesContextFactory
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1012)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
	at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:524)
	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:427)
	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:421)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:712)
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:420)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
        ..............
    Caused by: java.lang.ClassNotFoundException: javax.faces.context.FacesContextFactory
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
	at com.sun.enterprise.loader.CurrentBeforeParentClassLoader.loadClass(CurrentBeforeParentClassLoader.java:83)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 49 more
    ]]

This is most likely Catalina web container is looking for javax/faces/context/FacesContextFactory, but there is no such thing exist as it was replaced by jakarta/faces/context/FacesContextFactory in newer version of Payara 6 version. or there is some config file is not updated to support newer version JSF?

Please follow it up and advise how to get it right!

### Expected Outcome

1. Applications (EJB or WEB) that deployed in Payara server instance should be able to access lib file through Payara class loader hierarchy (lib or modules )in domain.

2. Any application server instance deployment should not affect DAS server.

### Current Outcome

1. Application (deployed on server instance) can't access objects (that developed as lib jar and added to domain)

2. Application deployment failure cause DAS server not restart properly

### Reproducer

for "Application (deployed on server instance) can't access objects (that developed as lib jar and added to domain)"

I tried add lib as common or app lib type by using [--type app], there is no one works
I tried to remove module-info.java and recompile lib jar and re-add it to domain. not work as well.
I checked application's bean.xml and make sure that application bean-discovery-mode as 'all'

for "Application deployment failure cause DAS server not restart properly"

In fact, DAS server is not restart after app deployment failure, 
worst case: have to re-create domain to restore DAS to work order

### Operating System

Rocky Linux 9.1

### JDK Version

idk 17.0.7

### Payara Distribution

Payara Server Full Profile

**Comment by cidylong** [comment]
Actually, DAS is still running, but Admin_UI not accessible as JSF implementation(Catalina web container not run properly) not load.

**Comment by cidylong** [comment]
@Elifzeynepedman , Highest priority is fix " Application Deployment failure cause DAS server not start properly." If you need, I will submit whole error message.

**Comment by cidylong** [comment]
In my understanding. Payara 6 class loader can't load custom lib jar properly, maybe because the lib jar without wellformed MANIFEST.MF to support class loader to scan "Export-Package:" section. 

I'm trying to develop a wellformed MANIFEST.MF jar to test it again.

**Comment by cidylong** [comment]
@Elifzeynepedman , I had re-developed a OSGi enabled java lib (with wellformed "Export-Package: ....." section in MANIFEST.MF) and add it to payara domain lib. Then configure hazelcast-config.xml to set correct map element and data-serializable-factory in serialization element. Restart payara domain from CLI (asadmin).

DAS server log as:

     [2023-06-17T09:03:02.037+1000] [Payara 6.2023.5] [INFO] [] [fish.payara.nucleus.hazelcast.HazelcastCore] [tid: _ThreadID=33 _ThreadName=RunLevelControllerThread-1686956580242] [timeMillis: 1686956582037] [levelValue: 800] [[
  Loading Hazelcast configuration from file: hazelcast-config.xml]]

     [2023-06-17T09:03:02.435+1000] [Payara 6.2023.5] [INFO] [] [org.glassfish.ha.store.spi.BackingStoreFactoryRegistry] [tid: _ThreadID=31 _ThreadName=RunLevelControllerThread-1686956580225] [timeMillis: 1686956582435] [levelValue: 800] [[
  Registered fish.payara.ha.hazelcast.store.HazelcastBackingStoreFactoryProxy for persistence-type = hazelcast in BackingStoreFactoryRegistry]]

but, DAS server is still running under without Admin_UI mode, as webcontainer not load properly. Error message is same as above.

Please find sever.log from attachment. 

[server.log](https://github.com/payara/Payara/files/11777272/server.log)

**Comment by Elifzeynepedman** [comment]
Hi @cidylong, 

Would you please test this in our latest release of Payara Server (6.2023.7).  Also, can you provide a simple-to-follow scenario on how to reproduce this on the latest version? A reproducer should ideally follow the SSCCE rules: http://www.sscce.org/. It will greatly help us to find the cause and fix it.

Thank you,
Elif

**Comment by cidylong** [comment]
@Elifzeynepedman , Sorry, I'm having disk issue in MacOS, I'm waiting for  my SSD disk come to replace it, after it arrived, I will update you.
