### PR TITLE
FISH-6033 Compilation Errors and Test Configuration Fixed

### PR DESCRIPTION
**Pull request by luiseufrasio**
## Description
Corrections done for
- JAX-WS-Tracing
- Client-certificate-validator
- MicroProfile Rest Client
- http

### Blockers
None

### New tests
None

### Testing Performed
mvn clean install -Ppayara-server-remote

### CODE REVIEW

**Comment by luiseufrasio** [comment]
jenkins test please

File: appserver/tests/pom.xml [hunk 1]
```diff
@@ -42,6 +42,13 @@
 -->
 
 <project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd"> <modelVersion>4.0.0</modelVersion>
+    <dependencies>
+        <dependency>
+            <groupId>jakarta.platform</groupId>
+            <artifactId>jakarta.jakartaee-web-api</artifactId>
+            <scope>compile</scope>
+        </dependency>
+    </dependencies>
```
Comment (Pandrex247) [inline appserver/tests/pom.xml:51]: This should be `provided` rather than `compile`.
It's also already defined for the relevant samples already.

```suggestion
```

**Review by Pandrex247 — CHANGES_REQUESTED** [review]
`test-domain-setup` doesn't seem to work
A few of these samples are integration tests, so don't get run by running `mvn test` - you need to run `verify` or `install`.

```
WARNING: The following warnings have been detected: WARNING: HK2 failure has been detected in a code that does not run in an active Jersey Error scope.
WARNING: Unknown HK2 failure detected:
MultiException stack 1 of 2
java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlElement
...
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlElement
MultiException stack 2 of 2
java.lang.IllegalStateException: Unable to perform operation: create on fish.payara.arquillian.jersey.jackson.internal.DefaultJacksonJaxbJsonProvider
```

File: appserver/tests/pom.xml (hunk 1 above)
Comment (luiseufrasio) [reply appserver/tests/pom.xml:51]: > This should be `provided` rather than `compile`. It's also already defined for the relevant samples already.

For sure, I think it was accidentaly changed by IDE

**Comment by luiseufrasio** [comment]
jenkins test please

**Review by Pandrex247 — CHANGES_REQUESTED** [review]
I'm still getting a couple of failures.

E.g. Jacc-per-app
```
SEVERE: While Deploying Application: 84cb5c2c-33af-497e-be05-3798e312badd --exit_code: FAILURE, message: Error occurred during deployment: Exception while loading the app : java.lang.IllegalStateException: ContainerBase.addChild: start: org.apache.catalina.LifecycleException: java.lang.IllegalStateException: PolicyConfigurationFactory com.sun.enterprise.security.jacc.provider.SimplePolicyConfigurationFactory is not an instance of fish.payara.jacc.JaccConfigurationFactory. Please see server.log for more details. [status: CLIENT_ERROR reason: Bad Request]
```

**Comment by luiseufrasio** [comment]
jenkins test please

File: appserver/tests/pom.xml [hunk 2]
```diff
@@ -42,6 +42,18 @@
...
 <project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd"> <modelVersion>4.0.0</modelVersion>
+    <dependencies>
+        <dependency>
+            <groupId>jakarta.platform</groupId>
+            <artifactId>jakarta.jakartaee-web-api</artifactId>
+            <scope>provided</scope>
+        </dependency>
+        <dependency>
+            <groupId>jakarta.xml.bind</groupId>
+            <artifactId>jakarta.xml.bind-api</artifactId>
```
Comment (Pandrex247) [inline appserver/tests/pom.xml:53]: I'm not a fan of this being defined up here.
It's going to end up being pulled into everything up here when not necessarily everything needs it e.g. payara-samples/test-utils, everything under quicklook.

I'd at least move this down to payara-samples, and remove the hardcoded version - the version is already defined in dependency management of [payara-bom](https://github.com/payara/Payara/blob/Payara6/api/payara-bom/pom.xml#L310)

**Review by Pandrex247 — CHANGES_REQUESTED** [review]

File: appserver/tests/payara-samples/samples/payara-expression-config-properties/src/main/resources/META-INF/payara-expression-config.properties [hunk 3]
```diff
@@ -1,4 +1,4 @@
 fish.payara.examples.expression.password=${ALIAS=wibbles}
 fish.payara.examples.expression.system=${fish.payara.examples.config.sources}
-fish.payara.examples.expression.recurse=${ENV=Dibbles}
-fish.payara.examples.expression.multiple=${ENV=Bibbly} and ${Bobbly}
+fish.payara.examples.expression.recurse=${Dibbles}
+fish.payara.examples.expression.multiple=${Bibbly} and ${Bobbly}
```
Comment (Pandrex247) [inline appserver/tests/payara-samples/samples/payara-expression-config-properties/src/main/resources/META-INF/payara-expression-config.properties:4]: This isn't correct - you're "fixing" the test by breaking it

File: appserver/tests/payara-samples/samples/payara-expression-config-properties/src/main/java/fish/payara/samples/microprofile/config/expression/ConfigServlet.java [hunk 4]
```diff
@@ -70,14 +70,14 @@
     @Override
     protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
         try {
-            updateEnv("Dibbles", "${Dabbles}");
+            updateEnv("Dabbles", "Dobbles");
```
Comment (Pandrex247) [inline appserver/tests/payara-samples/samples/payara-expression-config-properties/src/main/java/fish/payara/samples/microprofile/config/expression/ConfigServlet.java:73]: This isn't correct - you're "fixing" the test by breaking it

File: appserver/tests/payara-samples/samples/payara-expression-config-properties/src/main/java/fish/payara/samples/microprofile/config/expression/ConfigServlet.java [hunk 5]
```diff
@@ -70,14 +70,14 @@
...
             updateEnv("Bibbly", "Bibbles");
         } catch (ReflectiveOperationException ex) {
             throw new ServletException(ex);
         }
         Config config = ConfigProvider.getConfig();
         System.setProperty("fish.payara.examples.config.sources", "Tiddles!");
-        System.setProperty("Dabbles", "Dobbles");
+        System.setProperty("Dibbles", "${Dabbles}");
```
Comment (Pandrex247) [inline appserver/tests/payara-samples/samples/payara-expression-config-properties/src/main/java/fish/payara/samples/microprofile/config/expression/ConfigServlet.java:80]: This isn't correct - you're "fixing" the test by breaking it

**Review by Pandrex247 — CHANGES_REQUESTED** [review]

File: appserver/tests/pom.xml (hunk 2 above)
Comment (luiseufrasio) [reply appserver/tests/pom.xml:53]: Ok, I will move it to payara-samples,
but the version defined in payara-bom is <jaxb-api.version>3.0.1</jaxb-api.version>
Unhappily the test only works with 2.3.3
With 3.0.1 it result in
java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlElement

Comment (Pandrex247) [reply appserver/tests/pom.xml:53]: That to me stinks of something not being right.
If I'm not mistaken 2.3.3 is the version for Jakarta EE 8, 3.0.1 is the version for Jakarta EE 9 (namespace change)

File: appserver/tests/payara-samples/pom.xml [hunk 6]
```diff
@@ -566,6 +566,11 @@
             <artifactId>jakarta.ejb-api</artifactId>
             <scope>provided</scope>
         </dependency>
+        <dependency>
+            <groupId>jakarta.xml.bind</groupId>
+            <artifactId>jakarta.xml.bind-api</artifactId>
+            <version>2.3.3</version>
+        </dependency>
```
Comment (Pandrex247) [inline appserver/tests/payara-samples/pom.xml:573]: I still think this is wrong. 
If we have to pull this in as a compile scope dependency then something is asking for javax classes rather than jakarta and needs updating.

**Review by Pandrex247 — CHANGES_REQUESTED** [review]

File: appserver/tests/payara-samples/pom.xml (hunk 6 above)
Comment (luiseufrasio) [reply appserver/tests/payara-samples/pom.xml:573]: Yes, this solution was a workaround to run the test. The root problem is payara-container-common that depends on jersey-media-json-jackson. The last one has this statement in its pom.xml:
```
<exclusions>
<exclusion>
<groupId>jakarta.xml.bind</groupId>
<artifactId>jakarta.xml.bind-api</artifactId>
</exclusion>
<exclusion>
<groupId>jakarta.activation</groupId>
<artifactId>jakarta.activation-api</artifactId>
</exclusion>
</exclusions>
```
and
```
<dependency>
<!-- The last JAX-B API that has maven coordinates which do not collide with Jakarta coordinates -->
<!-- Do not update -->
<groupId>javax.xml.bind</groupId>
<artifactId>jaxb-api</artifactId>
<version>2.3.1</version>
<scope>test</scope>
</dependency>
```
I checked the newest version of this dependency and it also has these statements.

Comment (Pandrex247) [reply appserver/tests/payara-samples/pom.xml:573]: The newest version of the 3.0.x tags, 3.0.4, has a commit conveniently titled [Let Jackson use JAXB3](https://github.com/eclipse-ee4j/jersey/commit/4aa8007bc4d85b27acf4e6a0485ecfc905c707d7) - they changed the scope of the javax dependency to test scope and brought back in the jakarta dependency.

So I think the proper fix is to reapply our patches (if still applicable) to Jersey 3.0.4 to make 3.0.4.payara-p1 and have Arquillian/Payara use that.

File: appserver/tests/pom.xml [hunk 7]
```diff
@@ -42,6 +42,13 @@
 -->
 
 <project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd"> <modelVersion>4.0.0</modelVersion>
+    <dependencies>
+        <dependency>
+            <groupId>jakarta.platform</groupId>
+            <artifactId>jakarta.jakartaee-web-api</artifactId>
+            <scope>provided</scope>
+        </dependency>
+    </dependencies>
```
Comment (Pandrex247) [inline appserver/tests/pom.xml:51]: Still needs removing
```suggestion
```

**Review by Pandrex247 — CHANGES_REQUESTED** [review]

File: appserver/tests/pom.xml (hunk 7 above)
Comment (luiseufrasio) [reply appserver/tests/pom.xml]: done

**Review by Pandrex247 — APPROVED** [review]
Approved pending release of Arquillian Connectors 3.0.alpha4
