### ISSUE TITLE
NoClassDefFoundError for EllipticCurvesExtension when upgrading from 174 to Payara 5 RC1

### ISSUE THREAD

**Issue by youssefgh** [payara/Payara#2513]
# Description #
----------

Am trying to test my application that uses Payara 174. In the new Payara 5 RC
Am hitting an exception when calling :
``
httpsURLConnection.getInputStream();
``
There is a similar bug that i thinks that this is related to, see : https://github.com/eclipse-ee4j/grizzly-npn/issues/4

## Expected Outcome

I should get the inputstream with no exception

## Current Outcome

`
Caused by: java.lang.NoClassDefFoundError: sun/security/ssl/EllipticCurvesExtension
	at sun.security.ssl.Handshaker.getActiveProtocols(Handshaker.java:793)
	at sun.security.ssl.Handshaker.activate(Handshaker.java:549)
	at sun.security.ssl.SSLSocketImpl.kickstartHandshake(SSLSocketImpl.java:1492)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1361)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1413)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1397)
	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1564)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:263)
`

## Environment ##

- **Payara Version**: 5 RC1
- **Edition**: Full
- **JDK Version**: openjdk 1.8.0_151
- **Operating System**: Ubuntu 17

**Comment by lprimak** [comment]
I think that JDK 1.8.0u162 or later is required for SSL to work

**Comment by youssefgh** [comment]
This is already the last OpenJDK in Ubuntu repo. And running the same app by just going back to Payara 4 works 
Do you want me to try it with Oracle JDK instead ?

**Comment by lprimak** [comment]
Yes, the Ubuntu might not have the latest required JDK version

**Comment by youssefgh** [comment]
Same issue using jdk-8u162

**Comment by smillidge** [comment]
Are you sure you are getting the same issue on JDK8u162. Payara 5 requires JDK8u161 or above. The class name was changed in the JDK between those JDK versions.

**Comment by youssefgh** [comment]
Yes i switched java in my system so that 
`java -version` and `javac -version` print jdk-8u162
And added `AS_JAVA=/opt/jdk-8u162-linux-x64/jdk1.8.0_162` to payara5/glassfish/config/asenv.conf
BTW i run Payara through Netbeans. Am i still missing something ?
And thank you, i never knew the latest versions of Java 8 are required to run Payara 5

**Comment by smillidge** [comment]
Can you run a JVM report on your Payara instance to see what JVM it reports. It could be that NetBeans is spawning the Payara process using the same JDK version as NetBeans.

**Comment by youssefgh** [comment]
Yes that was it.
Netbeans forced its java version to Payara. Which misled my test results
Thanks @lprimak @smillidge so much for your help
Closing

**Comment by vsevoloddc** [comment]
Hi all. 
I have the problem, Glassfish 5 does not start after the command enable-secure-admin
Mike, thanks for your answer, but I already have the latest version of java
```
root@ubnt:~# java -version
openjdk version "1.8.0_162"
OpenJDK Runtime Environment (build 1.8.0_162-8u162-b12-0ubuntu0.16.04.2-b12)
OpenJDK 64-Bit Server VM (build 25.162-b12, mixed mode)
```
Can I have problems with the location of java?
Server log  [https://github.com/payara/Payara/issues/2661](url)

**Comment by smillidge** [comment]
Do you have a problem with GlassFish or with Payara Server?

**Comment by vsevoloddc** [comment]
I have a problem with glasfish 5 server.

**Comment by smillidge** [comment]
I would try with Payara Server then as it will work there.

**Comment by vsevoloddc** [comment]
Yes, Payara Server is work, but i need move application from Glassfish 2 to Glassfish 5, and I'm not sure that the application will start on a Payara Server.

**Comment by nandydesikan** [comment]
I actually got around this issue by copying over the jsse.jar that comes with underlying Linux OS jre to glassfish's jre.
For me, the class missing at runtime was sun.security.ssl.HandshakeStateManager.
Even EllipticCurvesExtension class is present in the jsse library.

Thanks,
Sriram

**Comment by nandydesikan** [comment]
> Hi all.
> I have the problem, Glassfish 5 does not start after the command enable-secure-admin
> Mike, thanks for your answer, but I already have the latest version of java
> 
> ```
> root@ubnt:~# java -version
> openjdk version "1.8.0_162"
> OpenJDK Runtime Environment (build 1.8.0_162-8u162-b12-0ubuntu0.16.04.2-b12)
> OpenJDK 64-Bit Server VM (build 25.162-b12, mixed mode)
> ```
> Can I have problems with the location of java?
> Server log [https://github.com/payara/Payara/issues/2661](url)

I actually got around this issue by copying over the jsse.jar that comes with underlying Linux OS jre to glassfish's jre.
For me, the class missing at runtime was sun.security.ssl.HandshakeStateManager.
Even EllipticCurvesExtension class is present in the jsse library.

Thanks,
Sriram
