### ISSUE TITLE
Payara-micro vs. hibernate 5 not working

### ISSUE THREAD

**Issue by sredelin** [payara/Payara#1662]
# payara-micro (4.1.2.172) not working with hibernate 5 (5.2.10.Final) #
----------

I am running payara-micro on dockerized environment deploying an app (war-file) including a hibernate 5 dependency to connect my object against the database (oracle 12).

## Expected Outcome
expected is a valid deployment

## Current Outcome
Currently I got the following exception
`payara-micro_1  | [2017-06-07T13:26:50.711+0000] [] [SEVERE] [NCLS-CORE-00026] [javax.enterprise.system.core] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1496842010711] [levelValue: 1000] [[
payara-micro_1  |   Exception during lifecycle processing
payara-micro_1  | java.lang.NoSuchMethodError: org.jboss.logging.Logger.debugf(Ljava/lang/String;I)V
payara-micro_1  |       at org.hibernate.query.spi.NamedQueryRepository.checkNamedQueries(NamedQueryRepository.java:151)
payara-micro_1  |       at org.hibernate.internal.SessionFactoryImpl.checkNamedQueries(SessionFactoryImpl.java:525)
payara-micro_1  |       at org.hibernate.internal.SessionFactoryImpl.<init>(SessionFactoryImpl.java:320)
payara-micro_1  |       at org.hibernate.boot.internal.SessionFactoryBuilderImpl.build(SessionFactoryBuilderImpl.java:452)
payara-micro_1  |       at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:889)
payara-micro_1  |       at org.hibernate.jpa.HibernatePersistenceProvider.createContainerEntityManagerFactory(HibernatePersistenceProvider.java:151)
payara-micro_1  |       at org.glassfish.persistence.jpa.PersistenceUnitLoader.loadPU(PersistenceUnitLoader.java:207)
payara-micro_1  |       at org.glassfish.persistence.jpa.PersistenceUnitLoader.<init>(PersistenceUnitLoader.java:114)
payara-micro_1  |       at org.glassfish.persistence.jpa.JPADeployer$1.visitPUD(JPADeployer.java:223)
payara-micro_1  |       at org.glassfish.persistence.jpa.JPADeployer$PersistenceUnitDescriptorIterator.iteratePUDs(JPADeployer.java:510)
payara-micro_1  |       at org.glassfish.persistence.jpa.JPADeployer.createEMFs(JPADeployer.java:230)
payara-micro_1  |       at org.glassfish.persistence.jpa.JPADeployer.prepare(JPADeployer.java:168)
payara-micro_1  |       at com.sun.enterprise.v3.server.ApplicationLifecycle.prepareModule(ApplicationLifecycle.java:926)
payara-micro_1  |       at com.sun.enterprise.v3.server.ApplicationLifecycle.deploy(ApplicationLifecycle.java:435)
payara-micro_1  |       at com.sun.enterprise.v3.server.ApplicationLifecycle.deploy(ApplicationLifecycle.java:220)
payara-micro_1  |       at org.glassfish.deployment.admin.DeployCommand.execute(DeployCommand.java:487)
payara-micro_1  |       at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:539)
payara-micro_1  |       at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:535)
payara-micro_1  |       at java.security.AccessController.doPrivileged(Native Method)
payara-micro_1  |       at javax.security.auth.Subject.doAs(Subject.java:360)
payara-micro_1  |       at com.sun.enterprise.v3.admin.CommandRunnerImpl$2.execute(CommandRunnerImpl.java:534)
payara-micro_1  |       at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:565)
payara-micro_1  |       at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:557)
payara-micro_1  |       at java.security.AccessController.doPrivileged(Native Method)
payara-micro_1  |       at javax.security.auth.Subject.doAs(Subject.java:360)
payara-micro_1  |       at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:556)
payara-micro_1  |       at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:1464)
payara-micro_1  |       at com.sun.enterprise.v3.admin.CommandRunnerImpl.access$1300(CommandRunnerImpl.java:109)
payara-micro_1  |       at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1846)
payara-micro_1  |       at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1722)
payara-micro_1  |       at com.sun.enterprise.admin.cli.embeddable.DeployerImpl.deploy(DeployerImpl.java:134)
payara-micro_1  |       at fish.payara.micro.impl.PayaraMicroImpl.deployAll(PayaraMicroImpl.java:1365)
payara-micro_1  |       at fish.payara.micro.impl.PayaraMicroImpl.bootStrap(PayaraMicroImpl.java:985)
payara-micro_1  |       at fish.payara.micro.impl.PayaraMicroImpl.main(PayaraMicroImpl.java:181)
payara-micro_1  |       at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
payara-micro_1  |       at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
payara-micro_1  |       at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
payara-micro_1  |       at java.lang.reflect.Method.invoke(Method.java:498)
payara-micro_1  |       at fish.payara.micro.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
payara-micro_1  |       at fish.payara.micro.boot.loader.Launcher.launch(Launcher.java:107)
payara-micro_1  |       at fish.payara.micro.boot.loader.Launcher.launch(Launcher.java:70)
payara-micro_1  |       at fish.payara.micro.boot.PayaraMicroLauncher.main(PayaraMicroLauncher.java:79)
payara-micro_1  |       at fish.payara.micro.PayaraMicro.main(PayaraMicro.java:358)
`

## Steps to reproduce (Only for bug reports) 
you can very easily run the standard payara-micro with executable jar and deploy a war file which includes a dependency to hibernate 5 and initialization of beans using hibernate.

## Environment ##
- **Payara Version**: 2.1.172
- **Edition**: 
- **JDK Version**: 
- **Operating System**: 
- **Database**: 

##  workaround ##
what helps me is the following
### the problem ###
is, that within hibernate 5 there is a dependency to jboss-logging-3.3.0.Final.
runtime jars in payara including dependency-jar "bean-validator.jar", which has also a dependency to jboss-logging but older version and directly including dependend Logger-class in this jar.
while loading the classpath the bean-validator will be loaded before jboss-logging.jar and Logger-class will not be reloaded in classpath (first come, first serve).
### what helps? ###
I changed the file-names within payaras runtime dependencies to "zzz_bean-validator.jar" and "zzz_bean-validator-cdi.jar".
Finally I extract the "jboss-logging.jar" out of jar, deleted the original one and reincluded the extracted one... (seems that changes the classpath as well....).
Now hibernate 5 works with payara ;)

**Comment by mulderbaba** [comment]
@sredelin bean-validator and bean-validator-cdi is coming from the hk2 and by upgrading to the latest of hk2 when it's out, we'll be replacing them with hibernate-validator and hibernate-validator-cdi. there is already a PR outstanding for it available at #1393. bean-validator and bean-validator-cdi re-bundle jboss-logging & hibernate-validator to make it an OSGI-friendly artifact. hopefully those classloading issues will be resolved soon.

**Comment by sredelin** [comment]
That's interesting. so payara is really depended to its dependencies and the dependencies of its dependencies...
Is there a possibillity to get a better sort while classloading of dependencies by default in payara artifact?

**Comment by mulderbaba** [comment]
@sredelin every project depends to its dependencies and their transitive dependencies actually. actually the problem here is with HK2 and its rebundling policy on jboss-logging, hibernate-validator artifacts. Creating a new jar by literally copying classes encounter problems. This will hopefully be resolved by upgrading to 2.5.x version of HK2 where they removed rebundling and used the actual artifacts.

**Comment by sredelin** [comment]
ok thanks

**Comment by mikecroft** [comment]
Closing since a fix is pending HK2 update
